version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        env_file:
            ./.env
        volumes:
            - praclientssr:/client
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
            ./.env
        depends_on:
            - postgres
            - client
        volumes:
            - praclientssr:/client:ro
        networks:
            - dotcom

    postgres:
      image: postgres:14     
      ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      env_file:
          ./.env
      volumes:
          - myapp:/var/lib/postgresql/data
      networks:
          - dotcom

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@admin.com
            PGADMIN_LISTEN_PORT: 80
        env_file:
            ./.env
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - dotcom

volumes:
    myapp:
    pgadmin-data:
    praclientssr:

networks:
    dotcom:
        driver: bridge
