version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        env_file:
            ./.env
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
            ./.env
        networks:
            - dotcom

    postgres:
      image: postgres:14     
      ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      env_file:
          ./.env
      volumes:
          - myapp:/var/lib/postgresql/data
      networks:
          - dotcom

volumes:
    myapp:

networks:
    dotcom:
        driver: bridge 