import { PlatoonsDataType } from '../types'

export const PlatoonsData: PlatoonsDataType[] = [
  {
    name: 'Стрелки Юж.Ф',
    resourceСost: 4,
    bringsResources: 1,
    tier: 1,
    type: 'Артиллеристы',
    nation: 'USSR',
    damage: 1,
    health: 5,
  },
  {
    name: 'Атиллеристы 17',
    resourceСost: 5,
    bringsResources: 0,
    tier: 3,
    type: 'Артиллеристы',
    nation: 'USSR',
    damage: 2,
    health: 7,
    specialProperties: {
      USSR: 'Нанесите 1 повреждение этому взводу и выбранному взводу протвника.',
    },
  },
  {
    name: 'Обеспечение 8А',
    resourceСost: 1,
    bringsResources: 0,
    tier: 2,
    type: 'Инженеры',
    nation: 'USSR',
    damage: 1,
    health: 4,
    specialProperties: {
      USSR: 'Когда этот взвод уничтожен - возьмите карту',
    },
  },
  {
    name: 'Spaher M',
    resourceСost: 4,
    bringsResources: 0,
    tier: 1,
    type: 'Разведчики',
    nation: 'German',
    defense: 2,
    health: 7,
  },
  {
    name: 'Nachrichten 1.PD',
    resourceСost: 2,
    bringsResources: 0,
    tier: 2,
    type: 'Разведчики',
    nation: 'German',
    defense: 1,
    health: 6,
    specialProperties: {
      German: '+2 к поддержке',
    },
  },
  {
    name: 'Signalers CA',
    resourceСost: 4,
    bringsResources: 1,
    tier: 3,
    type: 'Связисты',
    nation: 'USA',
    defense: 1,
    health: 7,
    specialProperties: {
      USA: '+1 к приросту ресурсов',
    },
  },
  {
    name: 'Fernschreiber K',
    resourceСost: 2,
    bringsResources: 0,
    tier: 3,
    type: 'Связисты',
    nation: 'German',
    damage: 1,
    health: 4,
    specialProperties: {
      German:
        'Если САУ атакует ваш штаб - она наносит на 1 повреждение меньше.',
    },
  },
  {
    name: 'Telephonists EF',
    resourceСost: 4,
    bringsResources: 0,
    tier: 2,
    type: 'Связисты',
    nation: 'USA',
    defense: 3,
    health: 6,
    specialProperties: {
      all: 'Когда защищает ваш штаб от атак лёгких танков - получает на 1 повреждение больше.',
      USA: '+3 к прочности.',
    },
  },
]
